---
# Central services registry
# Add new services here and update the orchestrate.yml with a new play
services:
  foo:
    group: foo_servers
    vars_file: vars/foo.yml
    order: 1
  bar:
    group: bar_servers
    vars_file: vars/bar.yml
    order: 2
  elephant:
    group: elephant_servers
    vars_file: vars/elephant.yml
    order: 3
